pipeline {
    agent any
    environment {
        IP = credentials('server_IP')
    }

    stages {
        // 1단계: Git 클론
        stage('Git Clone') {
            steps {
                git branch: 'dev-be', credentialsId: 'gitlab-credentials', url: 'https://lab.ssafy.com/s11-final/S11P31B105.git'
            }
            post {
                success { echo 'Repository clone 성공!' }
                failure { echo 'Repository clone 실패!' }
            }
        }

        // 2단계: secret.properties 파일 준비
        stage('Prepare secret.properties') {
            steps {
                script {
                    echo 'secret.properties 파일 준비 시작...'
                    withCredentials([file(credentialsId: 'secret-properties', variable: 'SECRET_FILE')]) {
                        sh 'cp $SECRET_FILE ./backend/spring/wassu/src/main/resources/secret.properties'
                    }
                }
            }
            post {
                success { echo 'secret.properties 파일 준비 완료!' }
                failure { echo 'secret.properties 파일 준비 실패!' }
            }
        }

        // 3단계: Docker 이미지 빌드
        stage('Build Docker Image') {
            steps {
                dir('./backend/spring/wassu') {  
                    sh 'docker build --no-cache -t spring .'
                }
                echo 'Docker 이미지 빌드 완료'
            }
            post {
                success { echo 'Docker 이미지 빌드 성공!' }
                failure { echo 'Docker 이미지 빌드 실패!' }
            }
        }

        // 4단계: 기존 Spring 컨테이너 중지 및 제거
        stage('Stop and Remove Existing Container') {
            steps {
                echo '기존 Spring 컨테이너 중지 및 제거 시작'
                sshagent(credentials: ['ec2']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no -p 2201 ubuntu@$IP "
                            docker-compose stop spring &&
                            docker-compose rm -f spring
                        "
                    '''
                }
                echo '기존 Spring 컨테이너 중지 및 제거 완료'
            }
            post {
                success { echo '컨테이너 중지 및 제거 성공' }
                failure { echo '컨테이너 중지 및 제거 실패' }
            }
        }

        // 5단계: 새로운 Spring 컨테이너 배포
        stage('Deploy New Container') {
            steps {
                echo 'Spring 서비스 배포 시작'
                sshagent(credentials: ['ec2']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no -p 2201 ubuntu@$IP "
                            docker-compose up -d --remove-orphans spring
                        "
                    '''
                }
                echo 'Spring 서비스 배포 완료'
            }
            post {
                success { echo '배포 성공' }
                failure { echo '배포 실패' }
            }
        }
    }

    post {
        always { echo '파이프라인 실행 완료' }
        success { echo '배포 성공' }
        failure { echo '배포 실패' }
    }
}
